Replace var with let in examples
mdn/webextensions-examples pull request #484
Opened 2022-03-12 01:57 UTC by rebloor

#### Summary
This change replaces the use of the `var` with `let` in the examples. This addresses the requirement identified in "Replace var with let in code snippets and examples" #11343 (which in turn was originally identified in discussions on "Use const in place of var" #11135).

After completing the global search and replace, a selection of examples was loaded and tested (approximately 10). Only [store-collected-images](https://github.com/mdn/webextensions-examples/tree/master/store-collected-images) was found to have issues, which were corrected by reverting the replace  of`var` with `let` in store-collected-images/webextension-plain/deps/uuidv4.js

2022-07-08 10:10 UTC, rpl requested changes
Hi @rebloor, I just took a look (to the diffs, I haven't expanded the context of all of them) and most of them looks ok, only two changes highlighted in the inline review comments below seems something that should be reverted.

2022-07-08 10:10 UTC, rpl commented on store-collected-images/webextension-with-webpack/webpack.config.js
> +    // to set this environment let to avoid reference errors.
this should be changed, the inline comment refers to OS environment variables.

2022-07-08 10:10 UTC, rpl commented on store-collected-images/webextension-plain/deps/idb-file-storage.js
> +    let mod = {
I think anything that is third party dependency for a webextensions-example (as in "coming from an outside repo") should be kept out of this change and left unmodified (and as a side note this part is not even part of that library, it is actually code injected automatically as part of the bundling).

2022-07-10 23:40 UTC, rebloor commented
@rpl thank you, I have reverted those changes.

2022-08-10 16:27 UTC, merged