Don't use <div /> as a button
mdn/webextensions-examples pull request #502
Opened 2022-10-23 20:44 UTC by Eik-S

As suggested by @rebloor this alignes the code to my changes in [the tutorial to this example](https://github.com/mdn/content/pull/21410)

2022-10-24 22:01 UTC, rebloor commented
@Eik-S Please note https://github.com/mdn/content/pull/21410#issuecomment-1278495245

2022-10-25 17:07 UTC, estelle requested changes
The class names aren't needed if using semantic elements. The CSS can be updated to read

```css
button {
  background-color: #E5F2F2;
}
button:hover {
  background-color: #CFF2F2;
}
[type="reset"] {
  background-color: #FBFBC9;
}
[type="reset"]:hover {
  background-color: #EAEA9D;
}

2022-10-25 17:07 UTC, estelle commented on beastify/popup/choose_beast.html
> +    <button class="button reset">Reset</button>
```suggestion
    <button>Frog</button>
    <button>Turtle</button>
    <button>Snake</button>
    <button type="reset">Reset</button>
```

2022-10-25 17:07 UTC, estelle commented on beastify/popup/choose_beast.css
>  .button {
```suggestion
button {
```

2022-10-25 17:19 UTC, Eik-S commented on beastify/popup/choose_beast.html
> +    <button class="button reset">Reset</button>
i like it! Thanks.

2022-10-25 17:58 UTC, Eik-S commented
Thanks @estelle 

I also adjusted the css selectors and a bug in the click listener.

2022-11-23 02:08 UTC, estelle approved these changes
Thank you!

2022-11-24 02:07 UTC, merged